name: Make Release Chart

on:
  workflow_call:
    inputs:
      APP_NAME:
        type: string
        required: true
      APP_VERSION:
        type: string
        required: true
      CHART_FOLDER:
        type: string
        required: true
      DOCKER_REGISTRY:
        description: "Docker registry for helm chart"
        type: string
        required: false
        default: "docker-registry.smartersales-dev.ru"
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

jobs:
  chart:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.3

      - name: Log into Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Update Chart
        uses: Slidem/inplace-envsubst-action@v1.2.2
        env:
          APP_NAME: ${{ inputs.APP_NAME }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
        with:
          working-directory: ${{ inputs.CHART_FOLDER }}
          fail_on_missing_variables: "true"
          search_input: |
            {
            "patterns": [".+.yaml"],
            "files": ["Chart.yaml"],
            "depth": 1
            }

      - name: Publish chart
        shell: bash
        run: |
          cd ${{ inputs.CHART_FOLDER }}
          helm registry login -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ inputs.DOCKER_REGISTRY }}
          helm package ./
          helm push ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tgz oci://${{ inputs.DOCKER_REGISTRY }}/helm-charts
